services:
  open-webui:
    # build:
    #   context: .
    #   args:
    #     OLLAMA_BASE_URL: "/ollama"
    #   dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${WEB_UI_PORT-3030}:8080
    # environment:
    #   - 'OLLAMA_BASE_URL=http://127.0.0.1:11434/ollama'
    #   - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
